export const SCHEMA_NORMALIZATION = [
  "# 阶段一产物模板",
  "",
  "## requirement.md",
  "```markdown",
  "# 需求文档: {需求标题}",
  "",
  "## 1. 功能概述",
  "{一段话精确描述这个需求要做什么}",
  "",
  "## 2. 功能范围",
  "### 包含",
  "- 功能点1",
  "### 不包含",
  "- 明确不做的事情1",
  "",
  "## 3. 外部依赖",
  "| 模块 | 依赖内容 | 接口 |",
  "|------|------|------|",
  "| 用户体系 | 复用登录态、用户ID | GetCurrentUser |",
  "```",
  "",
  "## fields.md",
  "```markdown",
  "# 字段定义",
  "## 实体: {实体名}",
  "| 字段名 | 类型 | 长度 | 必填 | 默认值 | 说明 | 校验规则 |",
  "|--------|------|------|:--:|------|------|------|",
  "| id | bigint | - | 是 | 自增 | 主键 | - |",
  "| name | string | 50 | 是 | - | 名称 | 1-50字符，非空 |",
  "| status | int | - | 是 | 1 | 状态 | 1启用 2禁用 |",
  "```",
  "",
  "## checkpoint.md",
  "```markdown",
  "# 验收条件",
  "## 正常流程",
  "- [ ] 验收点: {可测试的行为描述}",
  "## 异常流程",
  "- [ ] 验收点: 必填为空提示、不存在返回404",
  "## 边界条件",
  "- [ ] 验收点: 超长截断、并发处理",
  "```",
  "",
  "## boundary.md",
  "```markdown",
  "# 边界条件与约束",
  "## 1. 业务流程",
  "## 2. 权限定义",
  "| 角色 | 可执行操作 | 数据范围 |",
  "|------|------|------|",
  "| 管理员 | 增删改查 | 全部 |",
  "| 普通用户 | 查 | 自己的 |",
  "## 3. 数据量级",
  "| 维度 | 预估 |",
  "|------|------|",
  "| 数据总量 | 万级 |",
  "| 单页数量 | 20 |",
  "| 分页 | 是 |",
  "## 4. 边界条件",
  "| 场景 | 预期行为 |",
  "|------|------|",
  "| 字段为空 | 提示必填 |",
  "| 不存在 | 404 |",
  "| 并发 | 乐观锁 |",
  "## 5. 非功能需求",
  "| 维度 | 要求 |",
  "|------|------|",
  "| 响应时间 | < 200ms |",
  "| 安全 | 需登录校验 |",
  "| 日志 | 关键操作记录 |",
  "```",
].join("\n")

export const SCHEMA_DESIGN = [
  "# 阶段二产物模板：design.md",
  "",
  "章节结构：",
  "```",
  "一、数据库变更分析",
  "  1.1 现有表字段变更 | 表名 | 需新增字段 | 需修改字段 | 说明 |",
  "  1.2 新增表 | 表名 | 字段 | 索引 | 说明 |",
  "  1.4 确认清单（checkbox）",
  "二、后端代码分析",
  "  2.1 可复用函数 | 函数 | 文件:行号 | 是否需修改 | 修改说明 |",
  "  2.2 需新增函数 | 函数 | 文件 | 输入 | 输出 |",
  "  2.3 API设计 | Method | Path | Handler | 鉴权 | 说明 |",
  "  2.4 错误码 | 错误码 | HTTP | 说明 | 场景 |",
  "  2.5 确认清单（checkbox）",
  "三、前端代码分析",
  "  3.1 可复用组件 | 组件 | 文件 | 是否需修改 |",
  "  3.2 需新增组件 | 组件 | 文件 | Props |",
  "  3.3 路由 | 路由 | 组件 | 鉴权 |",
  "  3.4 确认清单（checkbox）",
  "四、边界条件与错误处理",
  "  | 场景 | 前端行为 | 后端行为 | HTTP |",
  "五、契约层代码",
  "  5.1 Entity (Go struct + gorm tag + json tag)",
  "  5.2 DTO (Go struct + binding tag)",
  "  5.3 TypeScript类型",
  "  5.4 SQL DDL",
  "  六、涉及项目",
  "  ## 涉及项目",
  "  - backend/api",
  "  - console",
  "七、确认结论（checkbox汇总）",
  "```",
].join("\n")

export const SCHEMA_API_JSON = [
  "# 阶段二产物模板：api.json (OpenAPI 3.0)",
  "",
  "必含顶层: openapi, info, servers, paths, components.securitySchemes, components.schemas",
  "每个接口必须: summary(中文), description, tags, security, parameters(含description和type), requestBody(含required和所有字段的description+校验规则), responses(200/400/401/403/404/500)",
  "components.schemas: 抽取重复结构用$ref引用，每个字段含type+description+example",
  "",
  "校验规则示例: minLength/maxLength/pattern/minimum/maximum/enum/default",
  "required数组: 列出所有必填字段名",
].join("\n")

export const SCHEMA_PLANNING = [
  "# 阶段三产物模板：plan.md",
  "",
  "章节结构：",
  "```",
  "一、Task DAG 依赖图（文本/Mermaid）",
  "  前置契约层: T1 → T2（类型/签名）",
  "  业务接口层: T3~T6 并行依赖 T1",
  "  前端UI层: 依赖 T2 + 对应接口 Task",
  "二、Task 契约",
  "  每个Task包含: 层级, 项目, 依赖, 上下文估算",
  "    输入契约（完整字段定义/类型引用）",
  "    输出（精确文件路径 + 函数/类型/组件签名）",
  "    实现要点（checkbox清单）",
  "    测试要求（场景列表）",
  "三、需求覆盖矩阵",
  "  | 设计点 | 来源 | 覆盖Task |",
  "四、执行单元",
  "  | 单元ID | 包含Task | 项目 | 依赖单元 |",
  "五、里程碑",
  "```",
].join("\n")

export const SCHEMA_EXECUTION = [
  "# 阶段四执行模型",
  "",
  "每个stevedore收到: Task契约(~200行) + 依赖签名(~100行) + 规范(~100行) < 500行",
  "",
  "Step 2: 写测试 → 运行 → RED",
  "Step 3: 写实现 → 运行 → GREEN",
  "Step 4: 编译+测试覆盖验证",
  "Step 5: 失败修复(≤3次)",
  "",
  "产出: execution_plan.json → .opencode/run/latest-execution-plan.json",
  "格式: { total_units, waves: [{wave, unit_ids, note}], tasks: [{unit_id, project, agent_description, prompt}] }",
  "work_dir 由引擎从 kanban.meta.worktree.projects 按 project 名自动注入。",
].join("\n")

export const SCHEMA_REVIEW = [
  "# 阶段五产物模板：review-log.md",
  "",
  "章节结构：",
  "```",
  "审查概览",
  "一、数据库 vs Entity 交叉检查",
  "  | 表名 | Entity文件 | 字段一致性 | 类型一致性 | 修复 |",
  "二、API 四方一致检查",
  "  api.json vs 后端 | 接口 | 路径 | 请求字段 | 响应字段 | 校验 |",
  "  api.json vs 前端 | 接口 | TS类型 | API调用 | 表单 |",
  "  api.json vs design.md 契约 | 接口 | Entity | DTO | TS类型 |",
  "三、跨 Task 契约对齐",
  "  输出契约验证 | Task | 文件存在 | 签名匹配 | 无遗漏 |",
  "  依赖输入验证 | 下游 | 上游 | 类型一致 |",
  "  接口隔离 | 无非法交叉引用 |",
  "四、测试与编译",
  "  测试 | 项目 | 总数 | 通过 | 失败 | 覆盖率 |",
  "  编译 | go build / tsc | ✅/❌ |",
  "五、问题汇总",
  "六、验收结论",
  "```",
].join("\n")

export const SCHEMA_TEST_REPORT = [
  "# 阶段六产物模板：test-report.md",
  "",
  "章节结构：",
  "```",
  "一、测试概览 | 类型 | 总数 | 通过 | 失败 | 覆盖率 |",
  "二、集成测试明细 | 端点 | 方法 | 测试内容 | 状态 | 响应时间 | 断言 | DB验证 |",
  "    测试内容：使用中文描述，如'用户创建-正常请求'、'用户编辑-参数校验失败'",
  "三、BUG追踪 | ID | 严重程度 | 位置 | 描述 | 修复记录 | 状态 |",
  "    严重程度: P1阻塞 P2功能缺陷 P3轻微",
  "四、E2E路径测试 | 路径 | 场景 | 状态 | 耗时 | 卡点 |",
  "五、修复统计 | 已修复 | 待修复 |",
  "```",
  "",
  "# 阶段六产物模板：bug-fix-suggestions.md",
  "",
  "仅有未修复BUG时生成此文件。",
  "",
  "章节结构：",
  "```",
  "一、BUG汇总 | Bug ID | 严重程度 | 类型 | 位置 | 问题描述 |",
  "二、修复建议详情",
  "    ### Bug ID",
  "    位置: 文件路径",
  "    E2E路径: 操作路径",
  "    问题描述: 详细说明",
  "    现状: 当前状态和影响",
  "    修复建议: 具体修复方案",
  "    参考代码: 代码示例（如有）",
  "    不能自动修复的原因: 为什么需要人工处理",
  "三、修复优先级建议 | 优先级 | Bug ID | 建议修复时间 |",
  "```",
].join("\n")

export const SCHEMA_CONTENT: Record<string, string> = {
  "normalization.md": SCHEMA_NORMALIZATION,
  "design.md": SCHEMA_DESIGN,
  "api.json.md": SCHEMA_API_JSON,
  "planning.md": SCHEMA_PLANNING,
  "execution.md": SCHEMA_EXECUTION,
  "review.md": SCHEMA_REVIEW,
  "test-report-template.md": SCHEMA_TEST_REPORT,
}
