// 阶段一~六的执行指令。每个阶段: 产物 → 1/2/3/4 要点 → 禁止。

export const DCT_NORMALIZATION = [
  "# 阶段一：需求澄清",
  "",
  "通过多轮追问将模糊需求澄清为结构化文档。每次只问 1-2 个问题。",
  "",
  "## 产物",
  "- requirement.md：功能概述、功能范围、外部依赖",
  "- fields.md：字段定义（名称、类型、必填、校验规则）",
  "- checkpoint.md：验收条件（可测试的 checklist）",
  "- boundary.md：业务流程、权限、数据量级、边界条件",
  "",
  "## 执行",
  "",
  "### 1. 追问循环",
  "按优先级逐维度追问，全部澄清后再产出文件。每次 1-2 个具体问题：",
  "",
  "| 优先级 | 维度 | 追问方向 |",
  "|:--:|------|------|",
  "| 1 | 功能范围 | 增删改查？包含/不包含？涉及模块？ |",
  "| 2 | 外部依赖 | 依赖哪些已有模块/系统/API？ |",
  "| 3 | 字段定义 | 所有字段名称、类型、必填、默认值、校验规则 |",
  "| 4 | 业务流程 | 状态流转？触发条件？关键操作步骤？ |",
  "| 5 | 权限 | 谁能操作？角色定义？权限点？ |",
  "| 6 | 数据量级 | 预期数据量？分页？导出？批量？ |",
  "| 7 | 边界条件 | 空状态？极端值？并发？错误处理？ |",
  "| 8 | 非功能需求 | 性能指标？安全要求？日志/审计？ |",
  "",
  "- 问题必须具体可答，避免开放式提问",
  "- 某维度不适用则跳过",
  "- 用户不清楚时记录默认选择并推进",
  "",
  "### 2. 汇总产出",
  "将追问结果写入 4 个产物文件。调用 captain_schema({stage:1}) 获取格式模板。",
  "",
  "## 禁止",
  "- 追问期间产出任何文件",
  "- 一次问超过 2 个问题",
  "- 跳过"功能范围"和"字段定义"两个维度",
].join("\n")

export const DCT_DESIGN = [
  "# 阶段二：方案设计",
  "",
  "对比真实数据库和现有代码，生成设计文档。不写实现代码，每条决策可独立确认。",
  "",
  "## 输入",
  "- requirement.md、fields.md、checkpoint.md、boundary.md",
  "",
  "## 产物",
  "- design-analysis.md：设计分析报告（含决策点）",
  "- design.md：方案设计文档（含确认清单），必须包含「## 涉及项目」节，列出本需求涉及的项目目录名（每行一个，用 - 前缀）",
  "- api.json：OpenAPI 3.0 接口定义",
  "- test-case.md：测试用例（覆盖所有验收点）",
  "",
  "## 执行",
  "",
  "### 1. 数据库变更分析",
  "必须连接真实数据库（MCP MySQL）：",
  "- 从 fields.md 提取实体名，查 INFORMATION_SCHEMA 获取表字段",
  "- 逐字段对比：已存在 / 需新增 / 需修改",
  "- 结果写入 design.md § 一",
  "",
  "### 2. 后端代码复用分析",
  "- Grep 搜索实体名、函数名",
  "- LSP 精确分析（hover/goToDefinition/findReferences）",
  "- 判断：可复用 / 需修改 / 需新增",
  "- 写入 design.md § 二",
  "",
  "### 3. 前端代码复用分析",
  "- Glob 搜索组件、hooks、页面",
  "- LSP 分析（documentSymbol/hover/findReferences）",
  "- 判断：可复用 / 可扩展 / 需新建",
  "- 写入 design.md § 三",
  "",
  "### 4. 设计决策确认",
  "- 生成 design-analysis.md，用 question 工具分组呈现决策点",
  "- 记录用户选择，等待确认",
  "",
  "### 5. 生成契约代码",
  "Go struct、DTO、TypeScript 类型、SQL DDL。写入 design.md § 五。",
  "",
  "### 6. 生成 api.json + test-case.md",
  "- api.json：OpenAPI 3.0 格式，调用 captain_schema({stage:2}) 获取规范",
  "- test-case.md：覆盖 checkpoint.md 每个验收点",
  "",
  "## 禁止",
  "- 跳过数据库连接",
  "- 写实现代码（只做设计决策）",
  "- 产出无对比依据的结论",
].join("\n")

export const DCT_PLANNING = [
  "# 阶段三：原子拆分",
  "",
  "拆为三层 Task（前置契约/业务接口/前端UI），生成 DAG + 每个 Task 的契约。",
  "",
  "## 输入",
  "- design.md、api.json、checkpoint.md、fields.md",
  "",
  "## 产物",
  "- plan.md：Task DAG + 契约 + 执行单元表",
  "",
  "## 三层模型",
  "| 层级 | 内容 | 并行性 |",
  "|------|------|:--:|",
  "| 前置契约 | Entity/DDL/DTO/TS类型 | 串行 |",
  "| 业务接口 | handler+service+route+测试 | 并行 |",
  "| 前端UI | 组件/页面/测试 | 依赖对齐后并行 |",
  "",
  "## 执行",
  "",
  "### 1. 提取 Task 清单",
  "- 前置契约：design.md §五 Entity/DTO → 1 个 Task",
  "- 业务接口：api.json 每个 endpoint → 1 个 Task",
  "- 前端UI：design.md §三 每个组件/页面 → 1 个 Task",
  "",
  "### 2. 分析依赖",
  "- 实体间依赖 → 前置契约内部串行",
  "- 接口对 Entity 的依赖 → 接口 Task 依赖前置契约",
  "- 前端对接口的依赖 → 组件 Task 依赖对应接口 Task",
  "",
  "### 3. 编写 Task 契约",
  "每个 Task 必须包含：",
  "- 层级、项目、依赖、输入契约",
  "- 输出：精确文件路径 + 函数/类型签名",
  "- 实现要点：checklist 格式编码清单",
  "- 测试要求：正常/异常/边界场景",
  "",
  "### 4. 生成执行单元",
  "同项目、无依赖冲突的 Task 可合并为一个执行单元：",
  "",
  "| 单元ID | Task | 项目 | 依赖 |",
  "|--------|------|------|------|",
  "| U-001 | T1 | api | - |",
  "| U-002 | T2 | console | U-001 |",
  "",
  "### 5. 写入 plan.md",
  "",
  "## 禁止",
  "- 业务接口层拆 handler 和 service 为两个 Task",
  "- 接口间有实现级依赖（只允许依赖 Entity/DTO）",
  "- 遗漏 design.md 中的设计点",
  "- Task 上下文 > 500 行或 < 30 行",
].join("\n")

export const DCT_EXECUTION = [
  "# 阶段四：TDD 执行调度",
  "",
  "读取 plan.md 编排波次，输出 execution_plan。只做调度，不写代码。",
  "",
  "## 执行",
  "",
  "### 1. 读取 plan.md",
  "- 提取所有执行单元和 Task 契约",
  "",
  "### 2. 编排波次",
  "- 按依赖拓扑排序分组为 wave",
  "- 同 wave 内互不依赖可并行，wave 间串行",
  "",
  "### 3. 生成 execution_plan",
  "为每个执行单元生成完整 prompt（输入契约 + 输出 + 实现要点 + 测试），",
  "写入 `.opencode/run/latest-execution-plan.json`：",
  "",
  "`work_dir` 字段由引擎根据 worktree 配置自动注入，你只需填 `project` 字段。",
  "",
  "```json",
  '{ "total_units": 6,',
  '  "waves": [',
  '    { "wave": 1, "unit_ids": ["U-001"], "note": "前置契约" },',
  '    { "wave": 2, "unit_ids": ["U-002","U-003"], "note": "并行" }',
  "  ],",
  '  "tasks": [{ "unit_id":"U-001","project":"backend/api","agent_description":"...","prompt":"..." }]',
  "}",
  "```",
  "",
  "## 禁止",
  "- 自己写代码",
  "- 跳过 plan.md 直接编造执行单元",
].join("\n")

export const DCT_REVIEW = [
  "# 阶段五：审查验收",
  "",
  "四层审查，逐层通过才进下一层。spec 是唯一事实来源，修复即改代码。",
  "",
  "## 输入",
  "- design.md、api.json、plan.md、checkpoint.md",
  "- 阶段四的代码产出",
  "",
  "## 产物",
  "- review-log.md：四层审查报告",
  "",
  "## 执行",
  "",
  "### 1. 数据库 vs Entity 交叉检查",
  "- 提取 Entity 的 gorm tag 字段",
  "- 查 INFORMATION_SCHEMA 获取列信息",
  "- 比对：字段存在性、类型匹配、json tag 一致",
  "- 重试 ≤ 3 次",
  "",
  "### 2. API 四方一致检查",
  "以 api.json 为基准，检查后端 handler、前端调用、design.md 契约：",
  "- 路径、方法、请求/响应字段匹配",
  "- 以 api.json 为准修改代码",
  "- 重试 ≤ 3 次",
  "",
  "### 3. 跨 Task 契约对齐",
  "验证 plan.md 每个 Task 产出：",
  "- 文件存在、签名匹配、无遗漏无多余",
  "- 下游引用的上游类型一致",
  "- 接口间无非法交叉引用",
  "- 重试 ≤ 3 次",
  "",
  "### 4. 测试与编译",
  "```bash",
  "go test -gcflags=all=-l ./... -v -cover && go build ./... && go vet ./...",
  "npx jest --coverage && npx tsc --noEmit",
  "```",
  "分支覆盖率 ≥ 80%，不足补测试。重试 ≤ 3 次。",
  "",
  "### 5. 输出 review-log.md",
  "含问题汇总和验收结论。",
  "",
  "## 禁止",
  "- 带失败进入下一层",
  "- 修改 api.json（它是事实来源）",
  "- 修改契约对齐代码（只能改代码对齐契约）",
  "- 不连真实数据库做第一层",
].join("\n")

export const DCT_TESTING = [
  "# 阶段六：集成测试 + E2E 测试",
  "",
  "基于 api.json 和 checkpoint.md 生成测试脚本，执行后输出 test-report.md。",
  "",
  "## 输入",
  "- design.md、api.json、checkpoint.md、review-log.md",
  "",
  "## 产物",
  "- test/{date}-{topic}/api_test.go：Go 集成测试脚本",
  "- test/{date}-{topic}/e2e.spec.ts：Playwright E2E 测试脚本",
  "- test/{date}-{topic}/test-report.md：测试报告 + BUG 追踪表",
  "- test/{date}-{topic}/bug-fix-suggestions.md：未修复BUG修复建议（仅有未修复BUG时生成）",
  "",
  "## 执行",
  "",
  "### 0. 前置准备",
  "1. 调用 skill('test-auth') 加载认证配置和 token",
  "2. 创建测试目录：`test/{YYYY-MM-DD}-{需求topic}/`（sailor 工作目录下）",
  "",
  "### 1. 提取测试范围",
  "- api.json → API 端点清单（含中文描述）",
  "- checkpoint.md → 验收场景列表",
  "",
  "### 2. 生成 Go 集成测试",
  "生成 `api_test.go`，覆盖每个 API 端点：",
  "- net/http/httptest + Gin，覆盖正常/参数校验/认证/异常",
  "- 测试内容列：使用中文描述（如'用户创建-正常请求'）",
  "",
  "**Token 写入**：",
  "- 从 test-auth skill 获取 JWT 密钥和用户信息",
  "- 直接在测试文件中定义 token 常量",
  "- 不依赖外部文件或环境变量",
  "",
  "### 3. 运行集成测试",
  "```bash",
  "cd test/{date}-{topic} && go test -gcflags=all=-l -v -cover ./api_test.go",
  "```",
  "",
  "### 4. 验证写操作数据库状态",
  "对于 POST/PUT/DELETE 等写操作，运行测试后使用 MCP MySQL 验证数据库状态：",
  "- 查询相关表，确认数据已正确写入/更新/删除",
  "- 验证字段值、状态、关联数据是否正确",
  "- 如发现数据不一致，记录为 BUG",
  "",
  "### 5. BUG 修复",
  "分析失败原因 → 修复代码 → 重跑测试 → 重新验证DB状态，≤ 3 次。",
  "",
  "### 6. 生成 Playwright E2E 测试",
  "生成 `e2e.spec.ts`，覆盖 checkpoint.md 每个验收场景：",
  "- 使用独立的 Playwright 测试脚本",
  "- Token 直接写在测试文件中",
  "- 不依赖外部配置",
  "",
  "### 7. 运行 E2E 测试",
  "```bash",
  "cd test/{date}-{topic} && npx playwright test e2e.spec.ts",
  "```",
  "",
  "### 8. 生成 test-report.md",
  "汇总：测试概览、API 明细（含测试内容列）、BUG 追踪表、E2E 路径结果、修复统计。",
  "",
  "### 9. 生成 bug-fix-suggestions.md（如有未修复BUG）",
  "检查 test-report.md 中的 BUG 追踪表，如有 status 为 ❌ 的未修复 BUG：",
  "1. 读取 schemas.ts 中的 SCHEMA_TEST_REPORT 获取 bug-fix-suggestions.md 模板格式",
  "2. 为每个未修复 BUG 生成修复建议详情，包含：",
  "   - 位置：接口路径或前端组件路径",
  "   - E2E路径：用户操作路径",
  "   - 问题描述：详细说明",
  "   - 现状：当前状态和影响",
  "   - 修复建议：具体修复方案",
  "   - 参考代码：代码示例（如有）",
  "   - 不能自动修复的原因：为什么需要人工处理",
  "3. 生成修复优先级建议",
  "",
  "## 质量标准",
  "- 每个端点 ≥ 1 个集成测试",
  "- 写操作（POST/PUT/DELETE）运行后必须使用 MCP MySQL 验证 DB 状态",
  "- 每个验收场景 ≥ 1 个 E2E 测试",
  "- BUG 必录，无法自动修复标注待修复",
  "- 未修复BUG必须生成 bug-fix-suggestions.md",
  "",
  "## 禁止",
  "- 跳过集成测试直接跑 E2E",
  "- 修改 api.json 预期行为",
  "- 删失败测试而非修复代码",
  "- BUG 不记录",
].join("\n")

export const STAGE_INSTRUCTIONS: Record<string, string> = {
  "阶段1": DCT_NORMALIZATION,
  "阶段2": DCT_DESIGN,
  "阶段3": DCT_PLANNING,
  "阶段4": DCT_EXECUTION,
  "阶段5": DCT_REVIEW,
  "阶段6": DCT_TESTING,
}
